"""Campaign runner — the serving layer for a fixture campaign (W6).

A *campaign* is a set of trials that share one fixture, one defense
configuration, and — critically — **one serving backend**. The runner owns the
model plane; the defense stack owns the action plane; neither reaches into the
other.

Serving layer
-------------
The serving layer is halctf's :class:`~halagent.router.ModelRouter` reused
unchanged (``~/halctf-agent/halagent/router.py``). It already does the three
things a campaign needs — retries with backoff on transport faults, one
model-plane telemetry record per attempt, and refusal classification per call
— and its ``OpenAICompatibleBackend`` speaks vLLM's native dialect. Pointing
it at the local affinity router on ``localhost:8080`` is configuration, not
new code.

Campaign affinity
-----------------
Every request carries ``X-Campaign-ID``. The affinity router in front of the
vLLM replicas uses it to pin a campaign to one backend, so the long shared
prefix of a campaign (system preamble, fixture description, tool surface)
stays resident in that replica's prefix cache. The header is injected by
wrapping the backend's ``_opener`` seam rather than by editing or subclassing
the backend, so the reused router keeps its upstream error semantics exactly.

Backend selection is **pre-registered per campaign**: a campaign names its
backend up front, that name goes in the run manifest, and it does not change
while the campaign runs. This is what makes affinity meaningful — a campaign
that changed backends mid-run would evict the prefix cache the header exists
to preserve, and would also mean the corpus was generated by more than one
model while the manifest named one.

Model refusal is a terminal outcome, not a reroute
--------------------------------------------------
When the serving model declines to produce a turn, the router classifies it
and this runner ends the trial with
:attr:`TrialOutcome.REFUSED_BY_MODEL`, recording the refusal type and the
step it happened on. It does **not** escalate to a more permissive backend.

That is a deliberate design decision with two independent reasons, and it is
recorded here so it is not re-litigated as an oversight:

1. *Measurement.* A refusal is data about the model under test. A run that
   walked a fallback ladder until something complied would record the
   behaviour of the most permissive backend on the ladder while the manifest
   named the campaign's model — precisely the failure this repo already
   guards against everywhere else, where a stand-in component must be
   identifiable as a stand-in from the record alone
   (``saster_defense/manifest.py``). Silently substituting the *serving*
   model is the same defect one plane up.
2. *Affinity.* Swapping backends mid-campaign discards the prefix cache that
   ``X-Campaign-ID`` exists to hold, so refusal-triggered escalation and
   campaign pinning cannot both be satisfied.

The honest way to compare two models is two campaigns, each pinned and each
labelled in its own manifest. If a pinned model refuses so often that a
fixture yields no usable trials, that is a finding about the pairing and the
refusal rate in :meth:`CampaignRunner.stats` reports it, rather than a
number to be routed around.

Reroute budget
--------------
Budget is charged on the **action plane**, by
:class:`saster_defense.BudgetLedger` inside ``DefenseStack.submit()``: every
attempted action costs ``base_cost``, and an action a layer blocks costs an
additional ``reroute_cost`` because the agent stalls and has to find another
route. An unpriced block would make blocking layers look free and skew the
ablation. This runner's job is to make sure that accounting actually runs —
it submits every attempt through the stack, treats a block as a reroute and
asks the agent for its next attempt, and stops the trial the moment the
ledger is exhausted. Nothing here charges budget itself; charging lives in
one place.

Not in scope for this module: the per-trial trajectory-record assembler (see
``docs/trajectory-assembly.md``), which joins these results with the oracle
verdict and the marker layer.
"""

from __future__ import annotations

import sys
import urllib.request
from collections.abc import Callable, Iterator, Sequence
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

from saster_defense import ActionRequest, ActionResult, DefenseStack

from .analyst import AnalystBackend

#: Header the affinity router reads to pin a campaign to one vLLM replica.
CAMPAIGN_HEADER = "X-Campaign-ID"

#: The local affinity router in front of the cluster's vLLM replicas.
DEFAULT_BASE_URL = "http://localhost:8080"

#: Where the reused halctf router lives when it is not already importable.
DEFAULT_HALAGENT_PATH = Path.home() / "halctf-agent"


class ServingUnavailable(RuntimeError):
    """The halctf serving layer could not be imported."""


def import_halagent_router(halagent_path: Path | str | None = None) -> Any:
    """Import halctf's ``halagent.router`` module and return it.

    The halctf agent is a sibling checkout rather than an installed
    distribution, so its parent directory is put on ``sys.path`` when the
    package is not already importable. Raises :class:`ServingUnavailable`
    with the path that was tried, so a missing checkout is a clear message
    rather than a bare ``ModuleNotFoundError`` from deep in the runner.
    """
    try:
        from halagent import router  # type: ignore[import-not-found]

        return router
    except ImportError:
        pass

    path = Path(halagent_path) if halagent_path is not None else DEFAULT_HALAGENT_PATH
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))
    try:
        from halagent import router

        return router
    except ImportError as exc:  # pragma: no cover — environment-dependent
        raise ServingUnavailable(
            f"halctf serving layer not importable from {path}; "
            "set halagent_path on ServingConfig"
        ) from exc


def campaign_opener(
    campaign_id: str,
    opener: Callable[..., Any] | None = None,
    extra_headers: dict[str, str] | None = None,
) -> Callable[..., Any]:
    """Wrap a urllib opener so every request carries ``X-Campaign-ID``.

    ``OpenAICompatibleBackend`` builds its own header dict but takes its
    opener as a field, so this seam adds campaign affinity without touching
    the reused backend's request construction or its error handling.
    """
    base = opener if opener is not None else urllib.request.urlopen
    headers = {CAMPAIGN_HEADER: campaign_id}
    if extra_headers:
        headers.update(extra_headers)

    def _open(req: Any, *args: Any, **kwargs: Any) -> Any:
        for key, value in headers.items():
            # add_header replaces on repeat, so retries stay idempotent.
            req.add_header(key, value)
        return base(req, *args, **kwargs)

    return _open


@dataclass(frozen=True)
class ServingConfig:
    """The one backend a campaign is pinned to, declared up front.

    ``campaign_id`` is both the affinity key and the manifest's campaign
    label, so the record and the routing decision cannot disagree.
    """

    campaign_id: str
    model: str
    base_url: str = DEFAULT_BASE_URL
    api_key: str | None = None
    timeout: float = 60.0
    chat_path: str = "/v1/chat/completions"
    max_retries: int = 2
    halagent_path: Path | str | None = None

    def as_manifest_block(self) -> dict[str, Any]:
        """The run manifest's ``serving`` block."""
        return {
            "role": "campaign_serving_layer",
            "campaign_id": self.campaign_id,
            "backend": "openai_compatible",
            "model": self.model,
            "base_url": self.base_url,
            "chat_path": self.chat_path,
            "affinity_header": CAMPAIGN_HEADER,
            "backend_pinned": True,
            "refusal_policy": "terminal",
            "max_retries": self.max_retries,
        }


def build_backend(
    config: ServingConfig,
    opener: Callable[..., Any] | None = None,
) -> Any:
    """Build the campaign's ``OpenAICompatibleBackend``, affinity header wired.

    ``opener`` is the injection point tests use; production leaves it ``None``
    and gets ``urllib.request.urlopen`` underneath the campaign wrapper.
    """
    router = import_halagent_router(config.halagent_path)
    return router.OpenAICompatibleBackend(
        base_url=config.base_url,
        model=config.model,
        api_key=config.api_key,
        timeout=config.timeout,
        name=f"campaign::{config.campaign_id}",
        chat_path=config.chat_path,
        _opener=campaign_opener(config.campaign_id, opener),
    )


def build_router(
    config: ServingConfig,
    telemetry: Any,
    opener: Callable[..., Any] | None = None,
    backend: Any | None = None,
) -> Any:
    """Build the reused :class:`~halagent.router.ModelRouter` for a campaign.

    ``backend`` lets a caller supply an already-built backend (a scripted one
    in tests); otherwise the pinned OpenAI-compatible backend is constructed
    from ``config``.
    """
    router_mod = import_halagent_router(config.halagent_path)
    return router_mod.ModelRouter(
        backend=backend if backend is not None else build_backend(config, opener),
        telemetry=telemetry,
        max_retries=config.max_retries,
    )


class TrialOutcome(str, Enum):
    """How a trial ended.

    ``REFUSED_BY_MODEL`` and ``SERVING_ERROR`` are distinct on purpose: a
    model that declined and a backend that fell over are different facts
    about a run, and collapsing them would hide a refusal rate behind an
    error rate.
    """

    COMPLETED = "completed"
    REFUSED_BY_MODEL = "refused_by_model"
    BUDGET_EXHAUSTED = "budget_exhausted"
    SERVING_ERROR = "serving_error"
    NO_ACTIONS = "no_actions"


@dataclass
class TrialResult:
    """One trial's model-plane and action-plane record.

    ``reroutes`` counts blocks that sent the agent looking for another route;
    it is the trial-local view of what the ledger charged.
    """

    trial_id: str
    outcome: TrialOutcome
    steps: int = 0
    reroutes: int = 0
    blocked_actions: list[ActionRequest] = field(default_factory=list)
    executed_actions: list[ActionRequest] = field(default_factory=list)
    detection_entries: list[dict] = field(default_factory=list)
    refusal_type: str | None = None
    refusal_step: int | None = None
    error: str | None = None
    budget: dict[str, int] = field(default_factory=dict)
    analyst_completeness: list[float] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "trial_id": self.trial_id,
            "outcome": self.outcome.value,
            "steps": self.steps,
            "reroutes": self.reroutes,
            "blocked_actions": [a.tool for a in self.blocked_actions],
            "executed_actions": [a.tool for a in self.executed_actions],
            "detection_entries": list(self.detection_entries),
            "refusal_type": self.refusal_type,
            "refusal_step": self.refusal_step,
            "error": self.error,
            "budget": dict(self.budget),
            "analyst_completeness": list(self.analyst_completeness),
        }


#: An action supplier yields the agent's next attempted action. It is called
#: again after a block — that call *is* the reroute. Returning ``None`` ends
#: the trial normally.
ActionSupplier = Callable[[int, ActionResult | None], ActionRequest | None]


def plan_supplier(actions: Sequence[ActionRequest]) -> ActionSupplier:
    """An :data:`ActionSupplier` that walks a fixed plan in order.

    Each call returns the next action regardless of whether the previous one
    was blocked, which models an agent that reroutes to its next planned
    approach. Used by tests and by fixture replays.
    """
    it: Iterator[ActionRequest] = iter(actions)

    def _next(step: int, previous: ActionResult | None) -> ActionRequest | None:
        return next(it, None)

    return _next


@dataclass
class CampaignRunner:
    """Drives trials for one campaign against one pinned backend.

    Parameters
    ----------
    serving
        The pinned backend declaration. Recorded in the manifest.
    stack
        The defense stack. Owns the budget ledger; this runner never charges
        budget itself, it only ensures every attempt goes through
        ``submit()`` so the ledger sees it.
    analyst
        Which analyst backend is in use, for the manifest. Defaults to
        "no analyst ran", which is recorded distinctly from one that ran.
    router
        The reused halctf ``ModelRouter``. Optional: a runner can drive the
        action plane alone, which is what the ablation sweep does.
    """

    serving: ServingConfig
    stack: DefenseStack
    analyst: AnalystBackend = field(default_factory=AnalystBackend.none)
    router: Any | None = None
    results: list[TrialResult] = field(default_factory=list)

    # -- model plane -------------------------------------------------------

    def generate(
        self,
        trial_id: str,
        step_index: int,
        messages: list[dict],
        params: dict | None = None,
    ) -> Any:
        """One model-plane call through the reused router.

        Returns the router's ``RoutedResult`` untouched — refusal
        classification and per-attempt telemetry are the router's job, and
        re-deriving either here would give the corpus two disagreeing
        sources for the same fact.
        """
        if self.router is None:
            raise ServingUnavailable(
                "CampaignRunner has no router; construct one with build_router()"
            )
        return self.router.generate(
            run_id=self.serving.campaign_id,
            challenge_id=trial_id,
            step_index=step_index,
            messages=messages,
            params=params or {},
        )

    # -- action plane ------------------------------------------------------

    def run_trial(
        self,
        trial_id: str,
        supplier: ActionSupplier,
        max_steps: int = 64,
    ) -> TrialResult:
        """Run one trial's action plane through the defense stack.

        Every attempt is submitted, so the ledger charges the attempt and —
        when a layer blocks — the reroute. A block does not end the trial: the
        supplier is asked for the agent's next attempt, which is the reroute
        the budget just paid for. The trial ends when the supplier is done,
        the step cap is hit, or the ledger is exhausted.
        """
        result = TrialResult(trial_id=trial_id, outcome=TrialOutcome.NO_ACTIONS)
        previous: ActionResult | None = None

        for step in range(max_steps):
            if self.stack.budget.exhausted:
                result.outcome = TrialOutcome.BUDGET_EXHAUSTED
                break

            action = supplier(step, previous)
            if action is None:
                # A supplier that never yielded anything is NO_ACTIONS, not a
                # completed trial — an empty trial and a finished one are
                # different facts about a run.
                result.outcome = (
                    TrialOutcome.COMPLETED if result.steps else TrialOutcome.NO_ACTIONS
                )
                break

            submitted = self.stack.submit(action)
            previous = submitted
            result.steps += 1
            result.detection_entries.extend(submitted.detection_entries)

            if submitted.blocked:
                # The ledger has just charged base + reroute. Asking the
                # supplier for the next attempt is that reroute.
                result.reroutes += 1
                result.blocked_actions.append(action)
            else:
                result.executed_actions.append(action)
        else:
            result.outcome = TrialOutcome.COMPLETED

        # A trial that exhausted the ledger reports that, even if the supplier
        # also happened to be finished.
        if self.stack.budget.exhausted and result.outcome is TrialOutcome.COMPLETED:
            result.outcome = TrialOutcome.BUDGET_EXHAUSTED

        result.budget = self.stack.budget.snapshot()
        self.results.append(result)
        return result

    def record_refusal(
        self,
        result: TrialResult,
        refusal_type: str | None,
        step_index: int,
    ) -> TrialResult:
        """Mark a trial as ended by a model refusal.

        Terminal by design — see this module's docstring. The refusal type and
        step are kept so the corpus can report *what* was declined and *when*,
        which is the information a fallback ladder would have destroyed.
        """
        result.outcome = TrialOutcome.REFUSED_BY_MODEL
        result.refusal_type = refusal_type
        result.refusal_step = step_index
        return result

    # -- reporting ---------------------------------------------------------

    def stats(self) -> dict[str, Any]:
        """Campaign-level counts, including the refusal rate.

        The refusal rate is reported rather than suppressed: if a pinned model
        declines a fixture often enough that the campaign yields little, that
        is the finding.
        """
        total = len(self.results)
        by_outcome: dict[str, int] = {}
        for r in self.results:
            by_outcome[r.outcome.value] = by_outcome.get(r.outcome.value, 0) + 1
        refused = by_outcome.get(TrialOutcome.REFUSED_BY_MODEL.value, 0)
        return {
            "trials": total,
            "by_outcome": by_outcome,
            "refusal_rate": (refused / total) if total else 0.0,
            "reroutes": sum(r.reroutes for r in self.results),
            "budget": self.stack.budget.snapshot(),
        }

    def run_manifest(self) -> dict[str, Any]:
        """The run manifest: defense layers, serving layer, analyst backend.

        The defense stack's own manifest is carried through unchanged and the
        two W6 blocks are added beside it, so a reader gets which layers ran,
        which model served the campaign, and which analyst analysed it from
        one artifact.
        """
        manifest = dict(self.stack.manifest())
        manifest["campaign_id"] = self.serving.campaign_id
        manifest["serving"] = self.serving.as_manifest_block()
        manifest["analyst"] = self.analyst.as_manifest_block()
        return manifest
