#!/usr/bin/env python3
"""GrrCON wrap: a README per run root (records and distinct per terminal
class per cell) and one index for the citable corpus. Generated; re-run to
regenerate. Read-only over the records."""
from __future__ import annotations

import collections
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
from saster_instrument.metrics import distinct_trajectories  # noqa: E402

ROOTS = {
    "w24": "first Stage 4 launch; halted by the operator after two cells per victim when D12 showed in the readback; kept as evidence, not analysed",
    "w24b": "the full 48-cell matrix per victim; 34 cells short on D13/D14, replaced by w24c in the analysed corpus",
    "w24c": "re-run of the 34 cells w24b lost, new run id, same paired seeds",
    "w25p": "addendum §P arm: Qwen under tool_choice required on the 30 cells where Ministral breached",
    "w26r": "addendum §R arm: R6 on l2, all and vendor-shaped, both families",
}


def read(p: Path) -> list[dict]:
    return [json.loads(line) for line in p.open() if line.strip()]


def main() -> None:
    index = []
    for root, why in ROOTS.items():
        for sp in sorted((REPO / "runs").glob(f"{root}_sweep_*/sweep_state.json")):
            st = json.loads(sp.read_text())
            tag = sp.parent.name.split("_sweep_", 1)[1]
            lines = [f"# {sp.parent.name}", "", f"Run id prefix `{root}`, victim `{st.get('victim', tag)}`. {why}.", "",
                     "Generated by `scripts/write_corpus_readmes_w27.py`. Distinct = unique tool-and-argument sequences.", "",
                     "| cell | records | distinct | per terminal class |", "|---|---|---|---|"]
            tot_r = tot_cells = 0
            for cid, c in sorted(st["cells"].items()):
                p = REPO / c["dir"] / "trajectories.jsonl"
                if not p.exists():
                    lines.append(f"| {cid} | 0 | 0 | (no records) |")
                    continue
                recs = read(p)
                tot_r += len(recs)
                tot_cells += 1
                by = collections.Counter(r["terminal_outcome"] for r in recs)
                per = ", ".join(f"{k} {v}/{distinct_trajectories([r for r in recs if r['terminal_outcome'] == k])}" for k, v in sorted(by.items()))
                lines.append(f"| {cid} | {len(recs)} | {distinct_trajectories(recs)} | {per} |")
            lines += ["", f"Cells with records: {tot_cells}; records: {tot_r}."]
            (sp.parent / "README.md").write_text("\n".join(lines) + "\n")
            index.append((sp.parent.name, tot_cells, tot_r, why))
    top = ["# The GrrCON corpus — index (generated)", "",
           "Citable total after AMENDMENT 19: **162 cells, 810 records** — the sweep (96 cells: w24b with w24c replacing its 34 lost cells), the §P arm (30) and the §R arm (36). "
           "Every record passed `carl_ops_trajectory.citable` (`runs/w25_stage5/citable_reload.json`).", "",
           "| run root | cells with records | records | why it exists |", "|---|---|---|---|"]
    top += [f"| {n} | {c} | {r} | {w} |" for n, c, r, w in index]
    top += ["", "The sweep's three run ids: `w24` (halted first launch, evidence only), `w24b` (the matrix), `w24c` (the 34-cell re-run). "
            "Each is a new run id because a re-run is a new result beside the old, never an overwrite."]
    (REPO / "runs" / "CORPUS_README.md").write_text("\n".join(top) + "\n")
    for n, c, r, _w in index:
        print(f"{n:<24} cells {c:>3} records {r:>4}")


if __name__ == "__main__":
    main()
